concurrency:
  cancel-in-progress: true
  group: ci-build-kubernetes-client-${{ github.ref }}
env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e
jobs:
  build:
    name: Java ${{ matrix.java }} Maven
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build Project
      run: ./mvnw ${MAVEN_ARGS} clean install
    - continue-on-error: true
      name: Check java-generator CLI
      run: 'chmod a+x java-generator/cli/target/java-gen

        java-generator/cli/target/java-gen --source=java-generator/core/src/test/resources/crontab-crd.yml
        --target=./tmp

        '
    strategy:
      matrix:
        java:
        - 8
        - 11
        - 17
        - 21
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
permissions:
  contents: read
