concurrency:
  cancel-in-progress: true
  group: ci-e2e-kubernetes-client-${{ github.ref }}
env:
  IT_MODULE: kubernetes-itests
  IT_REVISION: master
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e
jobs:
  buildWithoutTests:
    if: github.repository == 'fabric8io/kubernetes-client'
    name: BuildWithoutTests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache .m2 registry
      uses: actions/cache@v4
      with:
        key: cache-e2e-${{ github.sha }}-${{ github.run_id }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Setup Java 8
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Install Kubernetes Client
      run: ./mvnw ${MAVEN_ARGS} clean install -DskipTests -Djacoco.skip=true
  k8s-legacy:
    if: github.repository == 'fabric8io/kubernetes-client'
    name: K8S legacy
    needs: buildWithoutTests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Minikube-Kubernetes
      uses: manusa/actions-setup-minikube@v2.11.0
      with:
        github token: ${{ secrets.GITHUB_TOKEN }}
        kubernetes version: v1.12.10
        minikube version: v1.31.2
        start args: --force
    - continue-on-error: true
      name: Cache .m2 registry
      uses: actions/cache@v4
      with:
        key: cache-e2e-${{ github.sha }}-${{ github.run_id }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Setup Java 8
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Install and Run Integration Tests
      run: './mvnw ${MAVEN_ARGS} -Pitests -pl $IT_MODULE test -Dtest="io.fabric8.kubernetes.**"

        '
    strategy:
      fail-fast: false
  minikube_baremetal:
    if: github.repository == 'fabric8io/kubernetes-client'
    name: Baremetal K8S
    needs: buildWithoutTests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Minikube-Kubernetes
      uses: manusa/actions-setup-minikube@v2.11.0
      with:
        github token: ${{ secrets.GITHUB_TOKEN }}
        kubernetes version: ${{ matrix.kubernetes }}
        minikube version: v1.31.2
        start args: --force
    - continue-on-error: true
      name: Cache .m2 registry
      uses: actions/cache@v4
      with:
        key: cache-e2e-${{ github.sha }}-${{ github.run_id }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Setup Java 8
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Install and Run Integration Tests
      run: './mvnw ${MAVEN_ARGS} -Pitests -pl $IT_MODULE test -Dtest="io.fabric8.kubernetes.**"

        '
    strategy:
      fail-fast: false
      matrix:
        kubernetes:
        - v1.30.0
        - v1.29.0
        - v1.28.1
        - v1.27.5
        - v1.26.8
        - v1.25.13
        - v1.20.15
        - v1.19.16
  openshift:
    if: github.repository == 'fabric8io/kubernetes-client'
    name: OpenShift
    needs: buildWithoutTests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup OpenShift
      uses: manusa/actions-setup-openshift@v1.1.5
      with:
        github token: ${{ secrets.GITHUB_TOKEN }}
        oc version: ${{ matrix.openshift }}
    - continue-on-error: true
      name: Cache .m2 registry
      uses: actions/cache@v4
      with:
        key: cache-e2e-${{ github.sha }}-${{ github.run_id }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Setup Java 8
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Install and Run Integration Tests
      run: './mvnw ${MAVEN_ARGS} -Pitests -pl $IT_MODULE verify

        '
    strategy:
      fail-fast: false
      matrix:
        openshift:
        - v3.10.0
name: E2E Tests
on:
  repository_dispatch:
    types: trigger-ga___e2e-tests.yml
