concurrency:
  cancel-in-progress: true
  group: ci-e2e-http-client-tests-${{ github.ref }}
env:
  IT_MODULE: kubernetes-itests
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e
jobs:
  minikube:
    if: github.repository == 'fabric8io/kubernetes-client'
    name: K8S
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Minikube-Kubernetes
      uses: manusa/actions-setup-minikube@v2.11.0
      with:
        github token: ${{ secrets.GITHUB_TOKEN }}
        kubernetes version: ${{ matrix.kubernetes }}
        minikube version: v1.31.2
        start args: --force
    - continue-on-error: true
      name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Run Integration Tests
      run: './mvnw ${MAVEN_ARGS} -P"enable-snapshots" -P"httpclient-${{ matrix.httpclient
        }}" -Pitests -pl $IT_MODULE test -Dtest="io.fabric8.kubernetes.**"

        '
    strategy:
      fail-fast: false
      matrix:
        httpclient:
        - jdk
        - jetty
        - vertx
        kubernetes:
        - v1.28.1
        - v1.27.5
  openshift:
    if: github.repository == 'fabric8io/kubernetes-client'
    name: OpenShift
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup OpenShift
      uses: manusa/actions-setup-openshift@v1.1.5
      with:
        github token: ${{ secrets.GITHUB_TOKEN }}
        oc version: ${{ matrix.openshift }}
    - continue-on-error: true
      name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Run Integration Tests
      run: './mvnw ${MAVEN_ARGS} -P"enable-snapshots" -P"httpclient-${{ matrix.httpclient
        }}" -Pitests -pl $IT_MODULE verify

        '
    strategy:
      fail-fast: false
      matrix:
        httpclient:
        - jdk
        - jetty
        - vertx
        openshift:
        - v3.10.0
name: E2E HTTPClient Tests
on:
  repository_dispatch:
    types: trigger-ga___e2e-httpclient-tests.yml
