concurrency:
  cancel-in-progress: true
  group: ci-e2e-chaos-tests-${{ github.ref }}
env:
  CHAOS_MESH_VERSION: 2.6.0
  CHAOS_TESTS_MODULE: chaos-tests
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e
jobs:
  chaos-tests:
    if: github.repository == 'fabric8io/kubernetes-client'
    name: K8S Chaos Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Minikube-Kubernetes
      uses: manusa/actions-setup-minikube@v2.11.0
      with:
        github token: ${{ secrets.GITHUB_TOKEN }}
        kubernetes version: ${{ matrix.kubernetes }}
        minikube version: v1.31.2
    - continue-on-error: true
      name: Setup Java ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Setup Kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: ${{ matrix.kubernetes }}
    - continue-on-error: true
      name: Install Chaos Mesh
      run: 'curl -sSL https://mirrors.chaos-mesh.org/v${CHAOS_MESH_VERSION}/install.sh
        | bash

        kubectl wait --for=condition=Ready pods --all-namespaces --all --timeout=600s

        '
    - continue-on-error: true
      env:
        CHAOS_TEST: ${{ matrix.chaos-test }}
      name: Run Chaos Tests
      run: './mvnw ${MAVEN_ARGS} -Pitests -P"enable-snapshots" -P"httpclient-${{ matrix.http-client
        }}" verify -pl chaos-tests

        '
    strategy:
      fail-fast: false
      matrix:
        chaos-test:
        - network-delay.yaml
        - network-loss.yaml
        - network-duplicate.yaml
        http-client:
        - okhttp
        - jdk
        - jetty
        - vertx
        java-version:
        - 11
        - 17
        kubernetes:
        - v1.25.0
    timeout-minutes: 45
name: E2E Chaos Tests
on:
  repository_dispatch:
    types: trigger-ga___e2e-chaos-tests.yml
