concurrency:
  cancel-in-progress: true
  group: single-instance-for-persistent-cluster
env:
  FAILSAFE_TEST_GROUPS: OSCI
  IT_MODULE: kubernetes-itests
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e
jobs:
  e2e:
    if: github.repository == 'fabric8io/kubernetes-client'
    name: E2E OpenShift 4
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Install oc
      uses: redhat-actions/oc-installer@v1
    - continue-on-error: true
      name: Login to OpenShift
      run: 'oc login --server=${{ secrets.OSCI_SERVER }} --token=${{ secrets.OSCI_TOKEN
        }}

        '
    - continue-on-error: true
      name: Run Integration Tests
      run: './mvnw ${MAVEN_ARGS} -P"enable-snapshots" -Pitests -pl $IT_MODULE -Dgroups=$FAILSAFE_TEST_GROUPS
        verify

        '
name: E2E osci.io Tests
on:
  repository_dispatch:
    types: trigger-ga___e2e-osci-tests.yml
