concurrency:
  cancel-in-progress: true
  group: ci-go-kubernetes-client-${{ github.ref }}
jobs:
  generate-model:
    name: Kubernetes Model Generator Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
    - continue-on-error: true
      name: Setup Java 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Generate model
      run: make generate-model
    - continue-on-error: true
      name: Check No Schema file modified
      run: "git add .\nMODIFIED_KUBE_SCHEMA=`git status | grep -v 'validation-schema.json'\
        \ | grep 'kube-schema.json\\|src/generated/java' | wc -l`\nif [ $MODIFIED_KUBE_SCHEMA\
        \ -eq \"0\" ]; then\n  echo \"No Schema files modified. Build Success.\";\n\
        else\n  git status | grep -v 'validation-schema.json' | grep 'kube-schema.json\\\
        |src/generated/java'\n  echo \"Schema files modified. Build Failure\";\n \
        \ exit 1;\nfi;\n"
name: Go Generate Model
on:
  repository_dispatch:
    types: trigger-ga___gobuild.yml
permissions:
  contents: read
