concurrency:
  cancel-in-progress: true
  group: ci-docs-kubernetes-client-${{ github.ref }}
env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e
jobs:
  javadoc:
    name: JavaDocs
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Java 8
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Check Java Docs
      run: ./mvnw ${MAVEN_ARGS} clean install javadoc:jar -DskipTests -Pjavadoc-test
name: JavaDocs
on:
  repository_dispatch:
    types: trigger-ga___javadocs.yml
permissions:
  contents: read
