env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e ${{ github.event.inputs.additional_args
    }}
  OSSRHPASSWORD: ${{ secrets.OSSRHPASSWORD }}
  OSSRHUSERNAME: ${{ secrets.OSSRHUSERNAME }}
  RELEASE_MAVEN_ARGS: -Prelease -Denforcer.skip=true
  SIGNINGPASSWORD: ${{ secrets.SIGNINGPASSWORD }}
jobs:
  build-release-java-11-snapshot:
    if: contains('["manusa","rohanKanojia"]', github.actor)
    name: Release Java 11 SNAPSHOT
    needs: build-release-java-8-snapshot
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache .m2 registry
      uses: actions/cache@v4
      with:
        key: cache-snapshot-release-${{ github.sha }}-${{ github.run_id }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Setup Java 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        gpg-passphrase: SIGNINGPASSWORD
        gpg-private-key: ${{ secrets.SIGNINGKEY }}
        java-version: 11
        server-id: ossrh
        server-password: OSSRHPASSWORD
        server-username: OSSRHUSERNAME
    - continue-on-error: true
      name: Build and release Java 11 modules
      run: "./mvnw ${MAVEN_ARGS} ${RELEASE_MAVEN_ARGS}                           \
        \                                         \\\n  -pl \"httpclient-jdk\"   \
        \                                                                        \
        \             \\\n  -pl \"httpclient-jetty\"                             \
        \                                                         \\\n  -pl \"junit/kube-api-test\"\
        \                                                                        \
        \           \\\n  -pl \"junit/kube-api-test/core\"                       \
        \                                                       \\\n  -pl \"junit/kube-api-test/client-inject\"\
        \                                                                     \\\n\
        \  clean deploy\n"
    - continue-on-error: true
      name: Build and release BOM
      run: './mvnw ${MAVEN_ARGS} ${RELEASE_MAVEN_ARGS} clean sundr:generate-bom                                                                                                                                                                                                                                                                         &&

        ./mvnw ${MAVEN_ARGS} ${RELEASE_MAVEN_ARGS} gpg:sign-and-deploy-file -Prelease
        -Dgpg.passphrase=${{ secrets.SIGNINGPASSWORD }} -DrepositoryId=ossrh -Durl=https://oss.sonatype.org/content/repositories/snapshots/
        -DpomFile="target/classes/kubernetes-client-bom/pom.xml" -Dfile="target/classes/kubernetes-client-bom/pom.xml"            &&

        ./mvnw ${MAVEN_ARGS} ${RELEASE_MAVEN_ARGS} gpg:sign-and-deploy-file -Prelease
        -Dgpg.passphrase=${{ secrets.SIGNINGPASSWORD }} -DrepositoryId=ossrh -Durl=https://oss.sonatype.org/content/repositories/snapshots/
        -DpomFile="target/classes/kubernetes-client-bom-with-deps/pom.xml" -Dfile="target/classes/kubernetes-client-bom-with-deps/pom.xml"

        '
  build-release-java-8-snapshot:
    if: contains('["manusa","rohanKanojia"]', github.actor)
    name: Release Java 8 SNAPSHOT
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Cache .m2 registry
      uses: actions/cache@v4
      with:
        key: cache-snapshot-release-${{ github.sha }}-${{ github.run_id }}
        path: ~/.m2/repository
    - continue-on-error: true
      name: Setup Java 8
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        gpg-passphrase: SIGNINGPASSWORD
        gpg-private-key: ${{ secrets.SIGNINGKEY }}
        java-version: 8
        server-id: ossrh
        server-password: OSSRHPASSWORD
        server-username: OSSRHUSERNAME
    - continue-on-error: true
      name: Build and release Java 8 modules
      run: ./mvnw ${MAVEN_ARGS} ${RELEASE_MAVEN_ARGS} clean deploy
name: Release to SNAPSHOTS Maven Central
on:
  repository_dispatch:
    types: trigger-ga___release-snapshots.yaml
