concurrency:
  cancel-in-progress: true
  group: ci-sonar-kubernetes-client-${{ github.ref }}
env:
  MAVEN_OPTIONS: -B -C -V -ntp -Dhttp.keepAlive=false -e
jobs:
  sonar:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_LOGIN_TOKEN: ${{ secrets.SONAR_LOGIN_TOKEN }}
    name: Sonar
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Sonar
      run: make clean sonar
name: Sonar Scanner
on:
  repository_dispatch:
    types: trigger-ga___sonar.yml
permissions:
  contents: read
