concurrency:
  cancel-in-progress: true
  group: ci-license-kubernetes-client-${{ github.ref }}
env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e
jobs:
  style-check:
    name: License & Code Style Checks
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Setup Java 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Check License Headers
      run: ./mvnw ${MAVEN_ARGS} -Pitests -N license:check
    - continue-on-error: true
      name: Check Format (only on touched files)
      run: ./mvnw ${MAVEN_ARGS} -Pitests spotless:check
name: Style Checks
on:
  repository_dispatch:
    types: trigger-ga___style-checks.yml
permissions:
  contents: read
