concurrency:
  cancel-in-progress: true
  group: ci-win-kubernetes-client-${{ github.ref }}
jobs:
  build:
    name: Java ${{ matrix.java }} Maven
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build Project
      run: ./mvnw clean install
    strategy:
      matrix:
        java:
        - 17
name: Windows Build
on:
  repository_dispatch:
    types: trigger-ga___windows-build.yml
permissions:
  contents: read
